//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrintSample.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PrintSample.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   片面印刷 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Duplexing_OneSided {
            get {
                return ResourceManager.GetString("Duplexing_OneSided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   両面印刷（長辺） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Duplexing_TwoSidedLongEdge {
            get {
                return ResourceManager.GetString("Duplexing_TwoSidedLongEdge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   両面印刷（短辺） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Duplexing_TwoSidedShortEdge {
            get {
                return ResourceManager.GetString("Duplexing_TwoSidedShortEdge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   不明 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Duplexing_Unknown {
            get {
                return ResourceManager.GetString("Duplexing_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   印刷 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PrintPreview_Button {
            get {
                return ResourceManager.GetString("PrintPreview_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   部数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PrintPreview_Copies {
            get {
                return ResourceManager.GetString("PrintPreview_Copies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   オプション に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PrintPreview_Options {
            get {
                return ResourceManager.GetString("PrintPreview_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プリンターの設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PrintPreview_PrinterProperty {
            get {
                return ResourceManager.GetString("PrintPreview_PrinterProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プリンター に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PrintPreview_Printers {
            get {
                return ResourceManager.GetString("PrintPreview_Printers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   印刷 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PrintPreview_Title {
            get {
                return ResourceManager.GetString("PrintPreview_Title", resourceCulture);
            }
        }
    }
}
